#include "stdafx.h"
#include "gui/MCGuiGlobals.h"
#include "gui/MCGuiObject.h"

MCGuiOwned<MCGuiObject> FeatureScreen;
int FeatureScreenDone = 0;
int EscapedSmackerMovie = 0;
MCGuiFont* SystemFont = nullptr;
MCGuiFont* BlackFont = nullptr;
MCGuiFont* GreyFont = nullptr;
MCGuiFont* WhiteFont = nullptr;
MCGuiFont* RedFont = nullptr;
MCGuiFont* GreenFont = nullptr;
MCGuiFont* BlueFont = nullptr;
MCGuiFont* DimFont = nullptr;
MCGuiFont* YellowFont = nullptr;
MCGuiFont* YellowDropFont = nullptr;
MCGuiFont* BlueDropFont = nullptr;
MCGuiFont* MedBlackFont = nullptr;
MCGuiFont* MedGreyFont = nullptr;
MCGuiFont* MedWhiteFont = nullptr;
MCGuiFont* MedRedFont = nullptr;
MCGuiFont* MedGreenFont = nullptr;
MCGuiFont* MedBlueFont = nullptr;
MCGuiFont* MedDimFont = nullptr;
MCGuiFont* MedYellowFont = nullptr;
MCGuiFont* LgBlackFont = nullptr;
MCGuiFont* LgGreyFont = nullptr;
MCGuiFont* LgWhiteFont = nullptr;
MCGuiFont* LgRedFont = nullptr;
MCGuiFont* LgGreenFont = nullptr;
MCGuiFont* LgBlueFont = nullptr;
MCGuiFont* LgDimFont = nullptr;
MCGuiFont* LgYellowFont = nullptr;
std::array<std::array<MCGuiFont*, 3>, 10> Fonts = {};
bool GamePaused = false;
bool GameAsked = false;
int GWidth = 640;
int GHeight = 480;
int GBitDepth = 8;
int GFullScreen = 0;
int GStretchToFit = 0;
int GSoftwareCursor = 0;
bool GHiddenWindow = false;
int GRenderer = 0;
int GRendererPreference = 0;
int GShowFps = 0;
int GShowFpsPreference = 0;
bool GVSync = true;
bool ApplicationActive = true;
int32_t DisplayWidth = 0;
int32_t DisplayHeight = 0;
int OldMouseX = 0;
int OldMouseY = 0;
float FrameRate = 0.0f;
int64_t PerfStartTime = 0;
int64_t PerfStopTime = 0;
int64_t PrevStart = 0;
int64_t CountsPerSecond = 0;
int32_t LastX = 0;
int32_t LastY = 0;
std::string AppName;
std::string WindowTitle;
std::string PaletteName;
std::string StartupPakFile;
bool CheatsOn = false;
bool CantHitMe = false;
bool CantBlowSalvage = false;
bool BunnyStrikesOn = false;
bool Duh = false;
bool LockFrameRate = false;
bool TakeScreenShot = false;
uint32_t ScrollWait = 0;
int32_t DisplayProfileData = 0;
char KeySetting = 0;
bool ForceGatesClosed = false;
bool DrawTerrainGrid = false;
bool AndyFramerate = false;
std::recursive_mutex MouseCritSec;
volatile int InMouseCritSec = 0;
int MouseThreadStarted = 0;
