#pragma once

#ifndef MCREDUX_FIX_SHORT_HOTSPOT_PACKETS
#define MCREDUX_FIX_SHORT_HOTSPOT_PACKETS 0
#endif

#ifndef MCREDUX_FIX_ABL_UNINITIALIZED_STATICS
#define MCREDUX_FIX_ABL_UNINITIALIZED_STATICS 0
#endif

#ifndef MCREDUX_FIX_UNINITIALIZED_MECH_ACTOR
#define MCREDUX_FIX_UNINITIALIZED_MECH_ACTOR 0
#endif
